# Generated by Django 4.2.2 on 2024-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ranking',
            field=models.FloatField(default=0.0),
        ),
    ]
